/**
 * License Types
 * 许可证相关的类型定义
 */

/**
 * 激活错误代码枚举
 */
export enum ActivationErrorCode {
  // 格式错误
  INVALID_FORMAT = 'INVALID_FORMAT',
  INCOMPLETE_DATA = 'INCOMPLETE_DATA',
  MALFORMED_STRUCTURE = 'MALFORMED_STRUCTURE',
  
  // 验证错误
  SIGNATURE_VERIFICATION_FAILED = 'SIGNATURE_VERIFICATION_FAILED',
  EXPIRED_CODE = 'EXPIRED_CODE',
  PRODUCT_ID_MISMATCH = 'PRODUCT_ID_MISMATCH',
  DEVICE_FINGERPRINT_MISMATCH = 'DEVICE_FINGERPRINT_MISMATCH',
  UNSUPPORTED_VERSION = 'UNSUPPORTED_VERSION',
  
  // 限制错误
  ATTEMPT_LIMIT_EXCEEDED = 'ATTEMPT_LIMIT_EXCEEDED',
  DEVICE_LIMIT_EXCEEDED = 'DEVICE_LIMIT_EXCEEDED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  
  // 系统错误
  CRYPTO_ERROR = 'CRYPTO_ERROR',
  STORAGE_ERROR = 'STORAGE_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}
